import { BRAND_CSS, BRAND_ICON, FAVICON_LINK } from "../../branding.js";
import type { OpenApiDocument, OpenApiOperation } from "./openapi.js";

const escape = (value: unknown): string => String(value).replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
})[character]!);

// API descriptions support code spans while all source HTML remains escaped.
const renderProse = (value: unknown): string => escape(value).replace(/`([^`\n]+)`/g, "<code>$1</code>");

export const apiDocsCss = `
${BRAND_CSS}
:root{color-scheme:light dark;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace;font-size:14px;line-height:1.6;background:#faf9f6;color:#24231f}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-underline-offset:3px}a:hover{color:#625ac5}a:focus-visible,summary:focus-visible{outline:2px solid currentColor;outline-offset:4px}main{max-width:1080px;margin:0 auto;padding:36px 24px 64px}header{border-bottom:1px solid #c9c6bf;padding-bottom:24px;margin-bottom:30px}nav{display:flex;flex-wrap:wrap;gap:12px 24px}h1{font-size:clamp(24px,5vw,36px);line-height:1.2;font-weight:500;letter-spacing:-1px;margin:28px 0 14px}h2{font-size:18px;font-weight:500;margin:34px 0 14px}h3{font-size:14px;margin:0 0 8px}p{max-width:80ch;margin:10px 0}.muted{color:#6c6961}.start{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid #c9c6bf;margin:26px 0}.start>a{display:block;padding:18px;border-right:1px solid #c9c6bf;text-decoration:none}.start>a:last-child{border-right:0}.start strong{display:block;font-weight:500;margin-bottom:7px}.start span{font-size:12px;color:#6c6961}ol,ul{padding-left:22px}li{margin:6px 0}code{font-family:inherit;font-size:0.94em;overflow-wrap:anywhere}:not(pre)>code{padding:0 .25em;border:1px solid #8884;background:#8882;box-decoration-break:clone;-webkit-box-decoration-break:clone}pre{padding:16px;border:1px solid #c9c6bf;overflow-x:auto;background:#f1efea;max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere}pre code{font-size:12px}.reference{border-top:1px solid #c9c6bf;margin-top:26px}.group{border-bottom:1px solid #c9c6bf;padding:0 0 12px}.group>summary{font-size:16px;padding:16px 0;cursor:pointer}.endpoint{margin:0 0 8px;padding:0 0 0 18px}.endpoint>summary{cursor:pointer;overflow-wrap:anywhere}.verb{display:inline-block;min-width:58px;font-size:12px;font-weight:600}.endpoint p{font-size:12px;margin-left:58px}.endpoint .route{font-size:12px}.endpoint .auth{font-size:11px;color:#6c6961}.links{display:flex;flex-wrap:wrap;gap:10px 24px;padding:0;list-style:none}footer{margin-top:44px;padding-top:18px;border-top:1px solid #c9c6bf;font-size:12px}.skip{position:absolute;left:24px;top:-100px}.skip:focus{top:8px;background:#faf9f6;padding:8px}.note{border-left:2px solid #8b857b;padding-left:16px}dt{font-weight:600;margin-top:18px;scroll-margin-top:18px}dd{margin:4px 0 0;max-width:80ch}
.code-example{display:grid;grid-template-columns:minmax(0,1fr);grid-auto-columns:auto;align-items:start;gap:12px;margin:14px 0;padding:12px 16px;border:1px solid #c9c6bf;background:#f1efea}.code-example pre{grid-area:1/1;min-width:0;margin:0;padding:4px 0;border:0;background:transparent}.copy-code{grid-area:1/2;max-width:10ch;font:inherit;font-size:12px;line-height:inherit;padding:4px 10px;color:inherit;background:transparent;border:1px solid #888;cursor:pointer}
@media(max-width:620px){main{padding:24px 16px 40px}.start{grid-template-columns:1fr}.start>a{border-right:0;border-bottom:1px solid #c9c6bf}.start>a:last-child{border-bottom:0}nav{gap:8px 18px}.endpoint{padding-left:0}.endpoint p{margin-left:0}.verb{min-width:52px}pre{padding:12px}.code-example{gap:8px;padding:8px 12px}}
@media(prefers-color-scheme:dark){:root{background:#171715;color:#e7e4dc}.muted,.start span,.endpoint .auth{color:#aaa69c}header,footer,.start,.start>a,.reference,.group,pre,.code-example{border-color:#4d4b44}pre,.code-example{background:#20201c}.code-example pre{background:transparent}.skip:focus{background:#171715}a:hover{color:#bbb5ff}}

[hidden]{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.guide-shell{max-width:1400px;margin:auto;display:grid;grid-template-columns:240px minmax(0,1fr)}.guide-shell main{max-width:960px;width:100%;padding-top:36px;min-width:0}.guide-nav{padding:36px 24px;position:sticky;top:0;align-self:start;max-height:100vh;overflow:auto;border-right:1px solid #8885}.guide-nav nav,.guide-toc nav{display:flex;flex-direction:column;gap:10px;margin-top:24px}.guide-nav nav a{padding:8px 0;min-height:44px}.guide-nav [aria-current]{font-weight:bold;text-decoration-thickness:2px}.guide-shell article h1{font-size:clamp(28px,5vw,42px);line-height:1.2}.guide-shell h2,.guide-shell h3{scroll-margin-top:24px}.guide-shell article h2{margin-top:48px}.guide-shell table{display:block;max-width:100%;overflow:auto;border-collapse:collapse}.guide-shell td,.guide-shell th{text-align:left;padding:10px;border-bottom:1px solid #8885;vertical-align:top}.guide-toc{margin:24px 0;padding:14px;border:1px solid #8885}#endpoint-filter{display:block;width:100%;padding:12px;font:inherit;background:transparent;color:inherit;border:1px solid #888;margin:10px 0}button:focus-visible,input:focus-visible,pre:focus-visible{outline:2px solid #625ac5;outline-offset:3px}@media(max-width:800px){.guide-shell{display:block}.guide-nav{position:static;max-height:none;border-right:0;border-bottom:1px solid #8885;padding:20px}.guide-nav nav{flex-direction:row;flex-wrap:wrap;gap:4px 16px;margin-top:12px}.guide-shell main{padding:24px 20px}}
 .schema-fields{display:block;width:100%;max-width:100%;overflow:auto;border-collapse:collapse;font-size:12px}.schema-fields td,.schema-fields th{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #8885;overflow-wrap:anywhere}.schema-fields details{margin:10px 0}.endpoint h4{margin:24px 0 8px;font-weight:500}
`;

function authLabel(operation: OpenApiOperation): string {
  const auth = operation["x-auth"] as { scheme?: string; ownerOnly?: boolean; requiredBotScopes?: string[] } | undefined;
  return auth?.scheme === "public" ? "public" : auth?.ownerOnly ? "owner signature" : `signed ${auth?.requiredBotScopes?.join(", ") || "request"}`;
}

type DocObject = Record<string, unknown>;
const docObject = (value: unknown): DocObject => value && typeof value === "object" && !Array.isArray(value) ? value as DocObject : {};
function resolveDoc(value: unknown, spec: OpenApiDocument): DocObject {
  let result = docObject(value);
  for (let depth = 0; depth < 6 && typeof result.$ref === "string" && result.$ref.startsWith("#/"); depth++) {
    let target: unknown = spec;
    for (const part of result.$ref.slice(2).split("/")) target = docObject(target)[part.replaceAll("~1", "/").replaceAll("~0", "~")];
    const { $ref: _ref, ...siblings } = result;
    result = { ...docObject(target), ...siblings };
  }
  return result;
}
function schemaFields(value: unknown, spec: OpenApiDocument, depth = 0): string {
  const schema = resolveDoc(value, spec);
  const variants = schema.oneOf ?? schema.anyOf;
  if (Array.isArray(variants) && depth < 2)
    return variants.map((variant, index) => `<details><summary>Option ${index + 1}</summary>${schemaFields(variant, spec, depth + 1)}</details>`).join("");
  const properties = docObject(schema.properties);
  const required = Array.isArray(schema.required) ? schema.required : [];
  const rows = Object.entries(properties).map(([name, definition]) => {
    const field = resolveDoc(definition, spec);
    const values = field.enum ?? (field.const !== undefined ? [field.const] : undefined);
    const nested = field.type === "array" ? field.items : field;
    const children = depth < 2 && (docObject(nested).properties || docObject(nested).$ref)
      ? `<details><summary>Fields</summary>${schemaFields(nested, spec, depth + 1)}</details>` : "";
    return `<tr><th scope="row"><code>${escape(name)}</code></th><td>${escape(field.type ?? (field.oneOf || field.anyOf ? "one of" : "value"))}${field.format ? ` (${escape(field.format)})` : ""}<br>${required.includes(name) ? "required" : "optional"}</td><td>${renderProse(field.description ?? "")}${values ? `<p>Values: <code>${escape(JSON.stringify(values))}</code></p>` : ""}${field.default !== undefined ? `<p>Default: <code>${escape(JSON.stringify(field.default))}</code></p>` : ""}${children}</td></tr>`;
  });
  return rows.length ? `<table class="schema-fields"><thead><tr><th>Field</th><th>Type</th><th>Details</th></tr></thead><tbody>${rows.join("")}</tbody></table>` : `<p><code>${escape(schema.type ?? "See schema")}</code>${schema.description ? `: ${renderProse(schema.description)}` : ""}</p>`;
}
function endpointFields(operation: OpenApiOperation, spec: OpenApiDocument): string {
  const parameters = Array.isArray(operation.parameters) ? operation.parameters.map(value => resolveDoc(value, spec)) : [];
  const params = parameters.length ? `<h4>Parameters</h4><table class="schema-fields"><thead><tr><th>Name</th><th>Location</th><th>Details</th></tr></thead><tbody>${parameters.map(parameter => {
    const schema = resolveDoc(parameter.schema ?? docObject(docObject(parameter.content)["application/json"]).schema, spec);
    return `<tr><th scope="row"><code>${escape(parameter.name)}</code></th><td>${escape(parameter.in)}${parameter.required ? " / required" : " / optional"}</td><td>${renderProse(parameter.description ?? schema.description ?? schema.type ?? "JSON")}${schema.enum ? `<p><code>${escape(JSON.stringify(schema.enum))}</code></p>` : ""}</td></tr>`;
  }).join("")}</tbody></table>` : "";
  const request = docObject(docObject(docObject(operation.requestBody).content)["application/json"]).schema;
  const success = Object.entries(operation.responses).find(([status]) => /^2\d\d$/.test(status));
  const response = success ? resolveDoc(success[1], spec) : undefined;
  const result = docObject(docObject(response?.content)["application/json"]).schema;
  const showSchema = (title: string, value: unknown) => value ? `<h4>${title}</h4>${schemaFields(value, spec)}<details><summary>JSON schema</summary><pre tabindex="0"><code>${escape(JSON.stringify(resolveDoc(value, spec), null, 2))}</code></pre></details>` : "";
  return params + showSchema("Request body", request) + showSchema(`Response ${escape(success?.[0] ?? "")}`, result);
}

/** Server-rendered documentation with optional search and copy controls. Descriptions are escaped and never executed. */
export function apiDocsPage(spec: OpenApiDocument, surface?: "wallet"): string {
  const rows = Object.entries(spec.paths).flatMap(([path, methods]) => Object.entries(methods).map(([method, operation]) => ({ path, method: method.toUpperCase(), operation })));
  const groups = spec.tags.map((tag) => {
    const entries = rows.filter((row) => row.operation.tags.includes(tag.name));
    return `<details class="group" id="${escape(tag.name.toLowerCase())}"><summary>${escape(tag.name)} <span class="muted">(${entries.length})</span></summary><p class="muted">${renderProse(tag.description)}</p>${entries.map(({ path, method, operation }) =>
      `<details class="endpoint"><summary><span class="verb">${escape(method)}</span><span class="route">${escape(path)}</span> <span class="auth">${escape(authLabel(operation))}</span></summary><p>${renderProse(operation.summary)}</p>${operation.description ? `<p class="muted">${renderProse(operation.description)}</p>` : ""}${endpointFields(operation, spec)}<p><code>operationId: ${escape(operation.operationId)}</code></p></details>`).join("")}</details>`;
  }).join("");
  if (surface === "wallet") {
    const origin = escape(spec.servers[0]!.url);
    return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Signa API: accounts, wallet approvals and transaction execution."><title>Wallet API | Signa</title>${FAVICON_LINK}<script type="module" src="/assets/docs.js"></script><link rel="stylesheet" href="/assets/api.css"></head>
<body><a class="skip" href="#main">Skip to content</a><main id="main"><header><nav aria-label="Primary"><a href="/accounts">${BRAND_ICON} Signa</a><a href="/accounts">Accounts and bots</a><a href="https://juicebox.center/api">Juicebox protocol reference</a></nav><h1>Build with your wallet.</h1><p>Manage accounts and API access, prepare wallet transactions, approve spending and follow execution. Fresh owner approval is the default; a bot grant alone never authorizes spending.</p><nav aria-label="API resources"><a href="/api/v1/openapi.json">OpenAPI 3.1.2</a><a href="/api/v1/capabilities">Live capabilities</a><a href="#reference">Endpoint reference</a><a href="https://juicebox.center/api/docs/client">Shared SDK guide</a><a href="https://juicebox.center/api/docs/authentication">Signature format</a></nav></header>
<section id="start"><h2>Connect to Signa</h2><p>Check this deployment's supported chains and execution options before preparing a transaction.</p><div class="code-example"><button type="button" class="copy-code" hidden>Copy</button><pre><code>curl ${origin}/api/v1/capabilities</code></pre></div><p><a href="/accounts">Create an API connection</a>, download its file, then install the client:</p><div class="code-example"><button type="button" class="copy-code" hidden>Copy</button><pre><code>npm install ${origin}/api/client/juicebox-center-client-0.1.0.tgz
chmod 600 juicebox-connection.json
npx center account --connection juicebox-connection.json</code></pre></div><p>The connection file selects Signa's audience, <code>${origin}</code>. Keep its private key secret. The shared SDK and signature format retain their existing protocol names.</p><p>For contract catalogs, indexed history and project reads, use the <a href="https://juicebox.center/api">Juicebox Center protocol reference</a>. Center accounts and API connections are separate.</p></section>
<section id="write"><h2>Prepare → review → approve → check</h2><ol><li>Prepare a wallet plan from exact contract calls or a named transaction operation below.</li><li>Review its chain, recipient, value, calldata, fees, expiry and commitment. Simulate ready steps.</li><li>Approve with the wallet owner, or use an explicitly activated delegated session within its limits. Request authentication and spending approval remain separate.</li><li>Follow the existing plan, transaction hash or UserOperation to its canonical result. An uncertain response does not authorize replacement instructions.</li></ol><p><a href="https://juicebox.center/api/docs/smart-accounts">Shared wallet guide</a> / <a href="https://juicebox.center/api/docs/sessions">Delegated session guide</a>. Use this page and Signa's capabilities for the routes and features available here.</p></section>
<section id="reference"><h2>Endpoint reference</h2><p class="muted">Expand a group, then an endpoint. The local OpenAPI document contains exact parameters and schemas for Signa's account and wallet API.</p><label for="endpoint-filter">Find an endpoint</label><input id="endpoint-filter" type="search" placeholder="Search paths, operations, or permissions"><p id="endpoint-count" role="status" aria-live="polite"></p><div class="reference">${groups}</div></section>
<section id="errors"><h2>Errors and retries</h2><p>Errors use <code>application/problem+json</code>. Preserve <code>requestId</code>, check <code>code</code> and <code>retryable</code>, and honor <code>Retry-After</code>. For an authorized retry, keep the exact request bytes and idempotency key; use a fresh request nonce and signature. Reconcile an existing submission before attempting another.</p></section>
<section id="glossary"><h2>Wallet terms</h2><dl><dt id="glossary-grant">API grant</dt><dd>Time-limited API access for a bot. It does not grant wallet spending authority.</dd><dt id="glossary-session">Delegated session</dt><dd>Owner-approved authority to repeat specified actions within exact limits and expiry.</dd><dt id="glossary-paymaster">Gas / wei / paymaster</dt><dd>Gas measures transaction work. Wei is the smallest ETH unit. A paymaster sponsors supported network costs.</dd><dt id="glossary-receipt">Canonical receipt</dt><dd>Evidence that an exact transaction was included in the chain's accepted history. Its resulting state determines whether the intended action succeeded.</dd></dl></section>
<footer><a href="/api/v1/openapi.json">Machine-readable wallet API</a> / <a href="https://juicebox.center/api">Juicebox Center protocol reference</a></footer></main><p id="copy-status" role="status" aria-live="polite" class="sr-only"></p></body></html>`;
  }
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Juicebox V6 API: read projects, prepare transactions, and check their results."><title>Developer API | Juicebox Center</title>${FAVICON_LINK}<script type="module" src="/assets/docs.js"></script><link rel="stylesheet" href="/assets/api.css"></head>
<body><a class="skip" href="#main">Skip to content</a><main id="main"><header><nav aria-label="Primary"><a href="/">${BRAND_ICON} Juicebox Center</a><a href="/accounts">Accounts and bots</a><a href="/#agents">Assistant tools</a></nav><h1>Build with Juicebox.</h1><p>Read projects, prepare transactions, and follow results across chains. Start with a public request or connect your app in a few steps.</p><nav aria-label="API resources"><a href="/api/docs/user-journeys">Choose your journey</a><a href="/api/docs/project-intents">Project intents</a><a href="/api/v1/openapi.json">OpenAPI 3.1.2</a><a href="/api/v1/capabilities">Live capabilities</a><a href="/api/docs/api">Full guide</a><a href="/api/docs/ai-guide">Agent guide</a><a href="#glossary">Glossary</a></nav></header>
<section aria-label="Choose a starting point" class="start"><a href="#read"><strong>I need data →</strong><span>Read current values or search project history.</span></a><a href="#write"><strong>I need a transaction →</strong><span>Prepare, review, sign, then check the result.</span></a><a href="#reference"><strong>I am building an integration →</strong><span>Find request formats and supported actions.</span></a></section>
<section id="start"><h2>Your first request</h2><p>Explore supported chains and execution options. No account required.</p><div class="code-example"><button type="button" class="copy-code" hidden>Copy</button><pre><code>curl https://juicebox.center/api/v1/capabilities</code></pre></div><p>For protected requests, <a href="/accounts">create an API connection</a>, download its file, and install the client:</p><div class="code-example"><button type="button" class="copy-code" hidden>Copy</button><pre><code>npm install https://juicebox.center/api/client/juicebox-center-client-0.1.0.tgz
chmod 600 juicebox-connection.json
npx center account --connection juicebox-connection.json</code></pre></div><p>The client handles authentication. Your wallet separately approves spending.</p><p><a href="/api/docs/quickstart">Complete quickstart →</a> / <a href="/api/docs/client">Client workflows</a></p></section>
<section id="read"><h2>Choose a data source</h2><ul><li><strong>Read the blockchain:</strong> find the deployed contract and its <a href="#glossary-abi">interface (ABI)</a>, then call a read-only method. Results identify the verified block they describe.</li><li><strong>Search history:</strong> Bendystraw collects blockchain records into a searchable <a href="#glossary-indexer">index</a>. Choose real funds (<code>mainnet</code>) or test funds (<code>testnet</code>), filter to V6, and use the returned cursor to get the next page. Pages may reflect different blocks.</li><li><strong>Use a named operation:</strong> choose a project or developer task from the operations catalog and follow its required input format, called a schema.</li></ul><p>Project routes require <code>source=onchain</code> or <code>source=bendystraw</code>. Keep amounts and large integers as decimal strings. If a value could not be read, report it as unknown.</p><ul class="links"><li><a href="/api/v1/catalog/contracts">Contract catalog</a></li><li><a href="/api/v1/catalog/indexer">Indexer catalog</a></li><li><a href="/api/docs/contracts">Contract guide</a></li><li><a href="/api/docs/indexer">Indexer guide</a></li></ul></section>
<section id="write"><h2>Prepare → review → sign → check</h2><ol><li>Create a saved set of proposed transactions: a <a href="#glossary-plan">plan</a>. Use a named preparation or <code>contract_calls</code>. Sign the API request and include an <a href="#glossary-idempotency"><code>Idempotency-Key</code></a> so a retry can find the same result.</li><li>Review the exact chain, recipient, encoded instructions (<a href="#glossary-calldata">calldata</a>), native token amount, required earlier steps, block evidence, plan commitment and expiry. Test each ready step with a simulation.</li><li>Have the plan wallet sign the exact transaction. Submit those signed bytes with a fresh owner-signed API request, or a bot request carrying the owner’s exact approval.</li><li>Retrieve the plan with <code>refresh=true</code> to check what happened. Continue only when required earlier steps are confirmed. Check an uncertain submission by its existing transaction hash before retrying.</li></ol><p class="note">API access does not let a bot spend the owner's funds. Check capabilities for supported ways to send transactions and pay network costs. Steps on different chains can succeed or fail separately; confirmation on the sending chain does not prove funds arrived on the receiving chain.</p><p><a href="/api/docs/transactions">Plans, retries, confirmations and partial journeys</a> / <a href="/api/docs/sessions">Session lifecycle and quotas</a></p><p>A project can also be created without a transaction: publish a signed, frozen set of per-chain launch calls, then let Center's sponsor execute them on the supported rollups. See <a href="/api/docs/project-intents">project intents</a>.</p></section>
<section id="prepaid"><h2>Prepay for transactions across chains</h2><p>Prepare calls on supported chains and pay their network costs together. Center returns the exact calls for your wallet to approve, submits them, and prepares one funding transaction from the verified quote. Review and sign the funding transaction, then follow progress through Center.</p><p>Check whether funding already arrived before paying again. Verify each call on its destination chain; a quote or provider status alone does not prove payment or success. See the <a href="/api/docs/api">full guide</a> and <a href="/api/docs/ai-guide">agent workflow</a>.</p></section>
<section id="wallets"><h2>Use one wallet address across networks</h2><p>On <a href="/accounts">Accounts</a>, choose the networks for a separate transaction wallet. Review the shared setup and approve creation on each network. Then add prepared transactions to one review list and follow each network's result. Balances and permissions remain separate on each network. Your signed-in wallet pays the creation fees; supported later transactions can use sponsored network fees.</p><p>For unattended payments, approve a bot's allowed action, recipient, spending limits and expiry once on each network. After activation confirms, the bot can sign and send within those permissions without further owner prompts. Check <code>sessions.configuredChainIds</code> for networks where activation is available. Changes to the limits and transactions outside them need owner approval.</p><p><a href="/api/docs/smart-accounts">Wallet setup guide</a> / <a href="/api/docs/client#run-payments-without-another-owner-prompt">Run an unattended payment</a> / <a href="/api/v1/capabilities">Current capabilities</a></p></section>
<section id="reference"><h2>Endpoint reference</h2><p class="muted">Expand a group, then an endpoint. The OpenAPI document contains exact parameters and schemas; the contract method catalog supplies ABI-specific argument and output schemas.</p><label for="endpoint-filter">Find an endpoint</label><input id="endpoint-filter" type="search" placeholder="Search paths, operations, or permissions"><p id="endpoint-count" role="status" aria-live="polite"></p><div class="reference">${groups}</div></section>
<section id="errors"><h2>Errors and retries</h2><p>Errors use <code>application/problem+json</code> with <code>code</code>, <code>status</code>, <code>requestId</code> and <code>retryable</code>. Honor <code>Retry-After</code>. To retry the same request, keep its exact bytes and idempotency key. Use a new one-time request identifier (<a href="#glossary-nonce">nonce</a>) and API signature.</p><p>Retrying a plan step does not authorize changes to its instructions, network costs, or transaction nonce. Look up the stored transaction hash and check its state first.</p></section>
<section id="glossary"><h2>Glossary</h2><p>Look up a term here, then return to the step you were following.</p><dl>
<dt id="glossary-project">Project</dt><dd>A set of Juicebox rules, funds, and tokens. Identify it by both its chain ID and project ID.</dd>
<dt id="glossary-token">Project token / cash out</dt><dd>A project token records participation under a project’s rules. Cashing out gives up tokens permanently in exchange for project funds when those rules allow it. Tokens do not automatically give company ownership or a guaranteed return.</dd>
<dt id="glossary-revnet">Revnet</dt><dd>A Juicebox project with token rules scheduled at launch. Operators retain limited powers; see <a href="https://revnet.money/learn">the revnet guide</a>.</dd>
<dt id="glossary-contract">Smart contract</dt><dd>Code stored on a blockchain that runs when called. The code and its current settings determine what a call can do.</dd>
<dt id="glossary-ruleset">Ruleset</dt><dd>A project's rules for a period of time, including how payments create tokens and what can be paid out.</dd>
<dt id="glossary-terminal">Terminal</dt><dd>A contract that accepts and accounts for a project's payments and cash outs.</dd>
<dt id="glossary-hook">Hook</dt><dd>A contract a project calls to add behavior, such as giving a payer a collectible token.</dd>
<dt id="glossary-network">Mainnet / testnet</dt><dd>A network for real funds / a network for testing with test funds. A chain ID identifies the network.</dd>
<dt id="glossary-canonical">Canonical block</dt><dd>A block checked against the chain's current accepted history. A recent block can still be replaced by a chain reorganization.</dd>
<dt id="glossary-api">API / REST</dt><dd>An API lets programs request data or actions from another program. Center's REST API uses HTTP requests to named URLs.</dd>
<dt id="glossary-schema">Schema / audience</dt><dd>A schema defines a request or response’s exact fields and types. The authentication audience identifies the service a signature is intended for.</dd>
<dt id="glossary-rpc">RPC</dt><dd>A format for asking a remote computer to run a method. Ethereum JSON-RPC is used for blockchain reads and simulations here.</dd>
<dt id="glossary-mcp">MCP</dt><dd>Model Context Protocol: a shared format for connecting AI apps to tools and data.</dd>
<dt id="glossary-sdk">SDK</dt><dd>A software development kit: reusable code for building an app.</dd>
<dt id="glossary-abi">ABI</dt><dd>A contract interface that describes its methods, arguments, outputs, and events. Use the interface for the deployed contract you are calling.</dd>
<dt id="glossary-calldata">Calldata</dt><dd>The encoded instructions sent to a contract: which method to run and its arguments.</dd>
<dt id="glossary-indexer">Indexer / cursor</dt><dd>An indexer collects blockchain records so they can be searched. A cursor marks where the next page starts. Indexed data can lag behind the chain.</dd>
<dt id="glossary-metadata">Metadata / URI</dt><dd>Project details such as a name, description, and image. A URI identifies their location, such as an HTTPS or IPFS address.</dd>
<dt id="glossary-ipfs">IPFS / CID / pinning</dt><dd>IPFS is a shared file network. A CID identifies content; pinning keeps a copy available. A CID does not promise someone will keep hosting the file.</dd>
<dt id="glossary-grant">Bot grant / scope</dt><dd>A grant gives one bot time-limited API access. Scopes choose what it can do: read, plan, or relay. These are not wallet spending permissions.</dd>
<dt id="glossary-authority">Authority chain / principal</dt><dd>The authority chain is part of a Center account's identity. A principal is the owner or bot making an API request.</dd>
<dt id="glossary-plan">Plan / commitment</dt><dd>A plan saves proposed transactions and their required earlier steps. Its commitment is a hash that binds the exact plan being reviewed.</dd>
<dt id="glossary-idempotency">Idempotency key</dt><dd>An identifier that lets the service recognize a repeated request. Reuse it with the same bytes when retrying an operation that supports it.</dd>
<dt id="glossary-nonce">Nonce</dt><dd>A value that prevents reuse of a signed request. Each API attempt needs a fresh random nonce. A wallet transaction nonce instead orders that wallet's transactions.</dd>
<dt id="glossary-smart-wallet">Smart wallet / Safe / EOA</dt><dd>A smart wallet uses a contract to check approvals. Safe is one supported kind. An EOA is an account controlled directly by a private key.</dd>
<dt id="glossary-binding">Wallet binding</dt><dd>A verified link between a Center account and a smart wallet. Linking them does not grant a bot permission to spend.</dd>
<dt id="glossary-relay">Relay / bundler</dt><dd>A relay sends already signed transactions. A bundler submits smart-wallet UserOperations to the chain.</dd>
<dt id="glossary-operation">UserOperation / SafeOp</dt><dd>A UserOperation packages a smart-wallet action for submission. SafeOp is the exact approval document its Safe owners sign.</dd>
<dt id="glossary-session">Session / guard</dt><dd>A session is time-limited permission to repeat specified actions. A guard is a contract that enforces its limits. API access alone does not create a session.</dd>
<dt id="glossary-paymaster">Gas / wei / paymaster</dt><dd>Gas measures the work a transaction uses. Wei is the smallest ETH unit: 10¹⁸ wei equals 1 ETH. A paymaster sponsors supported network costs.</dd>
<dt id="glossary-receipt">Receipt</dt><dd>A blockchain record showing that a transaction was included and whether it succeeded or reverted. Check its events and resulting balances for the intended outcome.</dd>
<dt id="glossary-reconcile">Reconcile</dt><dd>Look up an existing submission and compare it with chain evidence to find out what happened before trying again.</dd>
</dl></section>
<footer><nav aria-label="More resources"><a href="/api/v1/openapi.json">Machine-readable API</a><a href="/api/docs/ai-guide">AI agent integration</a><a href="https://github.com/mejango/jbcenter">Source</a><a href="https://github.com/Bananapus/version-6">V6 repositories</a></nav></footer></main><p id="copy-status" role="status" aria-live="polite" class="sr-only"></p></body></html>`;
}
