import { BRAND_ICON, BRAND_CSS } from '../../branding.js';
/** Dedicated credential surface. All behavior and styles are served as same-origin assets. */
export function walletPage(signup = false, recovery = false, base = '/wallet', framed = false): string {
  return `<!doctype html>
<html lang="en"${framed ? ' class="framed"' : ''}><head><meta charset="utf-8"><meta name="wallet-base" content="${base}"><link rel="icon" type="image/svg+xml" href="${base}/assets/favicon.svg?v=signa"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer"><title>Your account | Signa</title>
<link rel="stylesheet" href="${base}/assets/wallet.css"><script type="module" src="${base}/assets/wallet.js"></script></head>
<body><main><a class="brand" href="${base || '/'}">${BRAND_ICON} <span class="brand-label">SIGNA</span></a>
<h1>Your account</h1>
<p id="wallet-destination" hidden></p>
<p id="wallet-status" role="status" aria-live="polite" aria-atomic="true" data-state="loading">Checking your wallet…</p>
<section id="wallet-account" aria-label="Connected account" hidden><dl id="wallet-details"><dt>Account address</dt><dd id="wallet-address"></dd><dt id="wallet-balance-label" hidden>Balance</dt><dd id="wallet-balance-row" hidden><details id="wallet-balance"><summary id="wallet-balance-total"></summary><ul id="wallet-balance-chains"></ul></details><button id="wallet-funds-open" class="link" type="button" hidden>Add funds</button>
<form id="wallet-funds" hidden novalidate><fieldset id="wallet-funds-asset"><legend>Add from Coinbase</legend>
<label class="choice"><input type="radio" name="asset" value="USDC" checked>USDC</label><label class="choice"><input type="radio" name="asset" value="ETH">ETH</label></fieldset><fieldset>
<label class="field">Amount in USD<input id="wallet-funds-amount" inputmode="decimal" autocomplete="off" placeholder="25"></label></fieldset>
<label id="wallet-funds-terms" class="choice" hidden><input id="wallet-funds-agree" type="checkbox"><span>For Apple Pay, I agree to Coinbase's <a href="https://www.coinbase.com/legal/guest-checkout/us" target="_blank" rel="noopener">Guest Checkout Terms</a>, <a href="https://www.coinbase.com/legal/user_agreement" target="_blank" rel="noopener">User Agreement</a> and <a href="https://www.coinbase.com/legal/privacy" target="_blank" rel="noopener">Privacy Policy</a>.</span></label>
<div class="actions"><button id="wallet-funds-applepay" type="submit" hidden>Apple Pay</button><button id="wallet-funds-coinbase" class="secondary" type="button">Coinbase account</button></div><p id="wallet-funds-cancel-row"><button id="wallet-funds-cancel" class="link" type="button">Cancel</button></p></form>
<div id="wallet-funds-pay" hidden></div></dd><dt id="wallet-passkey-label">Passkey</dt><dd id="wallet-passkey"></dd><dt>Networks</dt><dd><span id="wallet-networks">Base</span> <button id="wallet-networks-add" class="link" type="button" hidden>Add more</button></dd></dl>
<form id="wallet-networks-form" hidden><fieldset id="wallet-networks-family"><legend>Add your account to</legend>
<label class="choice"><input type="radio" name="family" value="mainnet" checked>Mainnets</label><label class="choice"><input type="radio" name="family" value="testnet">Testnets</label></fieldset>
<fieldset id="wallet-networks-choices"></fieldset>
<div class="actions"><button id="wallet-networks-deploy" type="submit">Deploy</button><button id="wallet-networks-cancel" class="link" type="button">Cancel</button></div></form>
<p id="wallet-devices-row"><button id="wallet-device-add" class="link" type="button">Add a device</button></p>
<section id="wallet-device" hidden aria-label="Add a device"><h2 id="wallet-device-title">Add a device</h2>
<p id="wallet-device-hint">Open this link on the other device. It creates its own passkey for this account; you approve it here.</p>
<div id="wallet-device-code" class="qr"></div><p><a id="wallet-device-link" target="_blank" rel="noopener"></a></p>
<div class="actions"><button id="wallet-device-approve" type="button" hidden>Approve this device</button></div></section></section>
<div class="actions"><button id="wallet-signin" type="button" hidden>Signa in</button>
<button id="wallet-retry" type="button" hidden>Retry</button>
<button id="wallet-device-cancel" class="link" type="button" hidden>Close</button>
<button id="wallet-logout" type="button" class="link" hidden>Sign out</button></div>
<div id="wallet-links">${signup ? `<a id="wallet-create" href="${base}/create" hidden>Signa up</a>` : ''}
${recovery ? `<a id="wallet-recover" href="${base}/recover" hidden>Recover</a>` : ''}</div>
<p id="wallet-open-row"><a id="wallet-open" href="${base || '/'}" hidden>Open as a page</a></p>
<noscript><p>Enable JavaScript to sign in with your passkey.</p></noscript>
</main></body></html>`;
}

export function walletCss(): string {
  return `${BRAND_CSS}
:root{--wallet-font:ui-monospace,SFMono-Regular,Consolas,monospace;--wallet-bg:#f5f4ee;--wallet-fg:#172019;--wallet-muted:#4b5a4e;--wallet-line:#172019;--wallet-accent:#172019;--wallet-accent-fg:#fff;--wallet-radius:0;--wallet-inset:calc(1.6rem - 1px + 1.75rem);color-scheme:light;font-family:var(--wallet-font);color:var(--wallet-fg);background:var(--wallet-bg)}
*{box-sizing:border-box}body{margin:0}main{width:min(100%,38rem);margin:clamp(1rem,10vh,6rem) auto;padding:1.5rem}
html.framed body{visibility:hidden}html.framed.themed body{visibility:visible}html.framed main{position:relative;display:flex;flex-direction:column;margin:0 auto;padding:1.25rem var(--wallet-inset)}html.framed .brand{display:none}html.framed h1{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;font-family:var(--wallet-heading-font,var(--wallet-font))}html.framed #wallet-status{min-height:0;margin:0 0 1rem;padding-right:3.25rem}html.framed #wallet-status::before{left:calc(-1 * var(--wallet-inset));width:var(--wallet-inset)}html.framed #wallet-links{margin-top:1rem}html.framed #wallet-status:is([data-state=brand],[data-brand]){order:1;margin:1.5rem 0 0;padding-right:0;color:var(--wallet-muted);font-size:.8rem;font-weight:400;line-height:1.3}html.framed #wallet-status:is([data-state=brand],[data-brand])::before{content:none}html.framed #wallet-status:is([data-state=brand],[data-brand]) a{text-decoration:none}
[hidden]{display:none!important}.brand{position:relative;gap:0;color:inherit;font-size:.8rem;letter-spacing:.06em}.brand-icon{position:absolute;right:calc(100% + .7rem);font-size:1.7em}h1{font-size:clamp(1.6rem,6vw,2.2rem);line-height:1.15;margin:2.5rem 0 1rem}
p{line-height:1.6;overflow-wrap:anywhere}#wallet-status{color:var(--wallet-fg);font-weight:700;min-height:3rem;margin:1.75rem 0;font-size:.95rem;position:relative}#wallet-status::before{content:"⚡\\FE0E";position:absolute;left:-1.05em;top:0;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:1.4em;line-height:1.143em;text-align:center;-webkit-text-stroke:.045em currentColor}#wallet-status[data-state=error]::before,#wallet-status[data-state=retry]::before{content:"!"}#wallet-status:empty::before{content:none}
#wallet-status[data-state=error],#wallet-status[data-state=retry]{color:#9c3028}#wallet-status a{color:inherit}fieldset{border:0;padding:0;margin:0 0 1.25rem}legend{color:var(--wallet-muted);font-size:.9rem;margin-bottom:.5rem}label.choice{display:flex;gap:.6rem;align-items:center;margin:.4rem 0}.choice input[type=radio]{appearance:none;width:1.25rem;height:1.25rem;min-height:1.25rem;flex:none;border:1px solid var(--wallet-line);border-radius:0;background:var(--wallet-bg);padding:0;cursor:pointer}.choice input[type=radio]:checked{background:var(--wallet-fg);box-shadow:inset 0 0 0 .22rem var(--wallet-bg)}#wallet-networks-family,#wallet-funds-asset{display:flex;gap:1.5rem;flex-wrap:wrap}#wallet-networks-family legend,#wallet-funds-asset legend{width:100%}#wallet-funds-asset{margin-bottom:.5rem}#wallet-funds legend{padding:0}#wallet-networks{line-height:1.6}button.link{all:unset;cursor:pointer;text-decoration:underline;color:var(--wallet-muted);margin-left:.75rem;font-size:.9rem}.actions button.link{margin:0;padding:0;width:auto}button.link:hover:not(:disabled){color:var(--wallet-fg);background:none}#wallet-networks-form{margin:1.5rem 0 2rem}#wallet-networks-form .actions{margin-top:1.5rem}@keyframes spin{to{transform:rotate(360deg)}}#wallet-status[data-state=busy]::before,#wallet-status[data-state=loading]::before,#wallet-status[data-state=checking]::before,#wallet-status[data-state=returning]::before{content:"⚡\\FE0E";display:inline-block;animation:spin 1s steps(8) infinite}dl{margin:0 0 1.5rem}dt{font-size:.8rem;color:var(--wallet-muted)}dd{margin:.5rem 0 1.2rem;overflow-wrap:anywhere}
.actions{display:flex;flex-wrap:wrap;gap:1rem;align-items:baseline}button{min-height:3rem;padding:.75rem 1rem;font:inherit;border:1px solid var(--wallet-accent);border-radius:var(--wallet-radius);background:var(--wallet-accent);color:var(--wallet-accent-fg);cursor:pointer;max-width:100%}
button.secondary{background:transparent;color:inherit}button:disabled{cursor:wait}button.link:disabled,button.secondary:disabled{opacity:.55}button:disabled:not(.link):not(.secondary){opacity:.55}@media(prefers-reduced-motion:reduce){button:disabled:not(.link):not(.secondary){animation:none}}button:hover:not(:disabled){background:color-mix(in srgb,var(--wallet-accent) 82%,var(--wallet-bg));color:var(--wallet-accent-fg)}button.secondary:hover:not(:disabled){background:color-mix(in srgb,var(--wallet-fg) 8%,var(--wallet-bg));color:inherit}
:focus-visible{outline:3px solid #5275d1;outline-offset:4px}.note{font-size:.8rem;color:var(--wallet-muted);margin-top:2rem}#wallet-links{display:flex;flex-wrap:wrap;gap:.75rem 1.5rem;margin-top:1.75rem}html.framed :is(#wallet-open,#signup-fullscreen){position:absolute;top:.65rem;right:calc(var(--wallet-inset) - .5rem);width:2.75rem;height:2.75rem;font-size:0;line-height:0;text-decoration:none;color:var(--wallet-muted)}html.framed :is(#wallet-open,#signup-fullscreen):hover{color:var(--wallet-fg)}html.framed :is(#wallet-open,#signup-fullscreen)::before,html.framed :is(#wallet-open,#signup-fullscreen)::after{content:"";position:absolute;width:.25rem;height:.25rem;border:0 solid currentColor}html.framed :is(#wallet-open,#signup-fullscreen)::before{top:1rem;right:1rem;border-top-width:1.5px;border-right-width:1.5px}html.framed :is(#wallet-open,#signup-fullscreen)::after{bottom:1rem;left:1rem;border-bottom-width:1.5px;border-left-width:1.5px}#wallet-links a,#wallet-open{color:var(--wallet-muted);font-size:.9rem;text-underline-offset:.15em}#wallet-links a:hover,#wallet-open:hover{color:var(--wallet-fg)}#wallet-open-row{margin:0}
.qr{width:min(100%,16rem);margin:1rem 0}.qr svg{width:100%;height:auto;display:block}#wallet-devices-row button.link{margin-left:0}#wallet-balance{display:inline}#wallet-balance summary{display:inline;cursor:pointer;text-decoration:underline dotted;text-underline-offset:.2em;list-style:none}#wallet-balance summary::-webkit-details-marker{display:none}#wallet-balance ul{list-style:none;margin:.6rem 0 0;padding:0;font-size:.85rem;color:var(--wallet-muted)}#wallet-balance li{margin:.25rem 0}#wallet-balance[open]+button.link{display:block;margin:.6rem 0 0}#wallet-funds-pay{margin:1rem 0 2rem}#wallet-funds-pay iframe{display:block;width:100%;height:36rem;border:0}#wallet-funds{margin:1rem 0 2rem}#wallet-funds .actions{margin-top:1.5rem}#wallet-funds-cancel-row{margin:1rem 0 0}#wallet-funds-cancel{margin-left:0}.field{display:block;margin:.5rem 0 1rem;font-size:.9rem;color:var(--wallet-muted)}.field input{display:block;width:100%;margin-top:.4rem;min-height:3rem;padding:.6rem .75rem;font:inherit;font-size:1rem;color:var(--wallet-fg);border:1px solid var(--wallet-line);border-radius:var(--wallet-radius);background:var(--wallet-bg)}.choice input[type=checkbox]{appearance:none;width:1.25rem;height:1.25rem;flex:none;margin:0;border:1px solid var(--wallet-line);border-radius:0;background:var(--wallet-bg);cursor:pointer}.choice input[type=checkbox]:checked{background:var(--wallet-fg);box-shadow:inset 0 0 0 .22rem var(--wallet-bg)}#wallet-funds-terms{align-items:flex-start;font-size:.85rem;line-height:1.5}#wallet-funds-terms a{color:inherit}#wallet-device{margin-bottom:1.5rem}#wallet-device h2{font-size:1.1rem;margin:1.5rem 0 .5rem}@media(max-width:40rem){main{padding-left:2.9rem;padding-right:2.9rem}#wallet-status::before{left:-1.25em}}@media(max-width:400px){main{padding:1.1rem 2.7rem}.actions{flex-direction:column;align-items:stretch}.actions button{width:100%}.actions button.link{width:auto;align-self:flex-start}}
html.framed :is(input:not([type=radio]):not([type=checkbox]),textarea,select,fieldset,dialog,.secret,.action-link){border-radius:var(--wallet-radius)}html.framed :is(input[type=radio],input[type=checkbox]){border-radius:min(var(--wallet-radius),4px)}html.framed main>.actions{padding-right:3.25rem}@media(max-width:400px){html.framed .actions{flex-direction:row;align-items:center}html.framed .actions button{width:auto}html.framed button:not(.link):not(.quiet){min-height:44px;padding:10px 20px}}`;
}
